/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fyy_jna_Hello */

#ifndef _Included_fyy_jna_Hello
#define _Included_fyy_jna_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fyy_jna_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fyy_jna_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
