/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-11-06")
public class ModelInfo implements org.apache.thrift.TBase<ModelInfo, ModelInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ModelInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ModelInfo");

  private static final org.apache.thrift.protocol.TField MODEL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("model_name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField GROUP_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("group_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField MODEL_INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("model_index", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ModelInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ModelInfoTupleSchemeFactory();

  public java.lang.String model_name; // required
  public java.lang.String group_name; // required
  public long model_index; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MODEL_NAME((short)1, "model_name"),
    GROUP_NAME((short)2, "group_name"),
    MODEL_INDEX((short)3, "model_index");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MODEL_NAME
          return MODEL_NAME;
        case 2: // GROUP_NAME
          return GROUP_NAME;
        case 3: // MODEL_INDEX
          return MODEL_INDEX;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MODEL_INDEX_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MODEL_NAME, new org.apache.thrift.meta_data.FieldMetaData("model_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GROUP_NAME, new org.apache.thrift.meta_data.FieldMetaData("group_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MODEL_INDEX, new org.apache.thrift.meta_data.FieldMetaData("model_index", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ModelInfo.class, metaDataMap);
  }

  public ModelInfo() {
  }

  public ModelInfo(
    java.lang.String model_name,
    java.lang.String group_name,
    long model_index)
  {
    this();
    this.model_name = model_name;
    this.group_name = group_name;
    this.model_index = model_index;
    setModel_indexIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ModelInfo(ModelInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetModel_name()) {
      this.model_name = other.model_name;
    }
    if (other.isSetGroup_name()) {
      this.group_name = other.group_name;
    }
    this.model_index = other.model_index;
  }

  public ModelInfo deepCopy() {
    return new ModelInfo(this);
  }

  @Override
  public void clear() {
    this.model_name = null;
    this.group_name = null;
    setModel_indexIsSet(false);
    this.model_index = 0;
  }

  public java.lang.String getModel_name() {
    return this.model_name;
  }

  public ModelInfo setModel_name(java.lang.String model_name) {
    this.model_name = model_name;
    return this;
  }

  public void unsetModel_name() {
    this.model_name = null;
  }

  /** Returns true if field model_name is set (has been assigned a value) and false otherwise */
  public boolean isSetModel_name() {
    return this.model_name != null;
  }

  public void setModel_nameIsSet(boolean value) {
    if (!value) {
      this.model_name = null;
    }
  }

  public java.lang.String getGroup_name() {
    return this.group_name;
  }

  public ModelInfo setGroup_name(java.lang.String group_name) {
    this.group_name = group_name;
    return this;
  }

  public void unsetGroup_name() {
    this.group_name = null;
  }

  /** Returns true if field group_name is set (has been assigned a value) and false otherwise */
  public boolean isSetGroup_name() {
    return this.group_name != null;
  }

  public void setGroup_nameIsSet(boolean value) {
    if (!value) {
      this.group_name = null;
    }
  }

  public long getModel_index() {
    return this.model_index;
  }

  public ModelInfo setModel_index(long model_index) {
    this.model_index = model_index;
    setModel_indexIsSet(true);
    return this;
  }

  public void unsetModel_index() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MODEL_INDEX_ISSET_ID);
  }

  /** Returns true if field model_index is set (has been assigned a value) and false otherwise */
  public boolean isSetModel_index() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MODEL_INDEX_ISSET_ID);
  }

  public void setModel_indexIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MODEL_INDEX_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MODEL_NAME:
      if (value == null) {
        unsetModel_name();
      } else {
        setModel_name((java.lang.String)value);
      }
      break;

    case GROUP_NAME:
      if (value == null) {
        unsetGroup_name();
      } else {
        setGroup_name((java.lang.String)value);
      }
      break;

    case MODEL_INDEX:
      if (value == null) {
        unsetModel_index();
      } else {
        setModel_index((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MODEL_NAME:
      return getModel_name();

    case GROUP_NAME:
      return getGroup_name();

    case MODEL_INDEX:
      return getModel_index();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MODEL_NAME:
      return isSetModel_name();
    case GROUP_NAME:
      return isSetGroup_name();
    case MODEL_INDEX:
      return isSetModel_index();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ModelInfo)
      return this.equals((ModelInfo)that);
    return false;
  }

  public boolean equals(ModelInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_model_name = true && this.isSetModel_name();
    boolean that_present_model_name = true && that.isSetModel_name();
    if (this_present_model_name || that_present_model_name) {
      if (!(this_present_model_name && that_present_model_name))
        return false;
      if (!this.model_name.equals(that.model_name))
        return false;
    }

    boolean this_present_group_name = true && this.isSetGroup_name();
    boolean that_present_group_name = true && that.isSetGroup_name();
    if (this_present_group_name || that_present_group_name) {
      if (!(this_present_group_name && that_present_group_name))
        return false;
      if (!this.group_name.equals(that.group_name))
        return false;
    }

    boolean this_present_model_index = true;
    boolean that_present_model_index = true;
    if (this_present_model_index || that_present_model_index) {
      if (!(this_present_model_index && that_present_model_index))
        return false;
      if (this.model_index != that.model_index)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetModel_name()) ? 131071 : 524287);
    if (isSetModel_name())
      hashCode = hashCode * 8191 + model_name.hashCode();

    hashCode = hashCode * 8191 + ((isSetGroup_name()) ? 131071 : 524287);
    if (isSetGroup_name())
      hashCode = hashCode * 8191 + group_name.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(model_index);

    return hashCode;
  }

  @Override
  public int compareTo(ModelInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetModel_name()).compareTo(other.isSetModel_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModel_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.model_name, other.model_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGroup_name()).compareTo(other.isSetGroup_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroup_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.group_name, other.group_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetModel_index()).compareTo(other.isSetModel_index());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModel_index()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.model_index, other.model_index);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ModelInfo(");
    boolean first = true;

    sb.append("model_name:");
    if (this.model_name == null) {
      sb.append("null");
    } else {
      sb.append(this.model_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("group_name:");
    if (this.group_name == null) {
      sb.append("null");
    } else {
      sb.append(this.group_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("model_index:");
    sb.append(this.model_index);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ModelInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ModelInfoStandardScheme getScheme() {
      return new ModelInfoStandardScheme();
    }
  }

  private static class ModelInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ModelInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ModelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MODEL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.model_name = iprot.readString();
              struct.setModel_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GROUP_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.group_name = iprot.readString();
              struct.setGroup_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MODEL_INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.model_index = iprot.readI64();
              struct.setModel_indexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ModelInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.model_name != null) {
        oprot.writeFieldBegin(MODEL_NAME_FIELD_DESC);
        oprot.writeString(struct.model_name);
        oprot.writeFieldEnd();
      }
      if (struct.group_name != null) {
        oprot.writeFieldBegin(GROUP_NAME_FIELD_DESC);
        oprot.writeString(struct.group_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MODEL_INDEX_FIELD_DESC);
      oprot.writeI64(struct.model_index);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ModelInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ModelInfoTupleScheme getScheme() {
      return new ModelInfoTupleScheme();
    }
  }

  private static class ModelInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ModelInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ModelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetModel_name()) {
        optionals.set(0);
      }
      if (struct.isSetGroup_name()) {
        optionals.set(1);
      }
      if (struct.isSetModel_index()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetModel_name()) {
        oprot.writeString(struct.model_name);
      }
      if (struct.isSetGroup_name()) {
        oprot.writeString(struct.group_name);
      }
      if (struct.isSetModel_index()) {
        oprot.writeI64(struct.model_index);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ModelInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.model_name = iprot.readString();
        struct.setModel_nameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.group_name = iprot.readString();
        struct.setGroup_nameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.model_index = iprot.readI64();
        struct.setModel_indexIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

